name: check_site

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install requests discord.py beautifulsoup4

      - name: Download last hash
        id: download-hash
        uses: actions/download-artifact@v4
        with:
          name: last-hash
        continue-on-error: true # Keep this, but handle the missing file more explicitly

      - name: Restore hash file
        run: |
          if [ -d "last-hash" ] && [ -f "last-hash/last_hash.txt" ]; then # Check if directory exists
            cp last-hash/last_hash.txt .
          else
            echo "No previous hash found. Starting fresh." # Add this line
          fi

      - name: Run monitor
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DEBUG_ID: ${{ secrets.DEBUG_ID }}
        run: python cbse.py

      - name: Upload new hash
        uses: actions/upload-artifact@v4
        with:
          name: last-hash
          path: last_hash.txt