name: check_site

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Required for commit & push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install requests discord.py beautifulsoup4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest last_hash.txt (optional safety)
        run: git pull origin main || true

      - name: Run monitor
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DEBUG_ID: ${{ secrets.DEBUG_ID }}
        run: python cbse.py

      - name: Commit updated hash
        run: |
          git add last_hash.txt
          git commit -m "Update last_hash.txt [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Push failed (e.g. protected branch)"
