name: check_site

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install requests discord.py beautifulsoup4

      - name: Run monitor
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DEBUG_ID: ${{ secrets.DEBUG_ID }}
        run: python cbse.py

      - name: Display contents of last_hash.txt
        run: cat last_hash.txt  # For debugging the contents of last_hash.txt

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if last_hash.txt changed
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes detected, committing last_hash.txt..."
            git add last_hash.txt
            git commit -m "Update last_hash.txt after checking CBSE site"
            git push origin HEAD:main
          else
            echo "No changes in last_hash.txt"
          fi
